/*
 * API v1
 * DocSpring is a service that helps you fill out and sign PDF templates.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.docspring.client.model;

import com.docspring.client.model.CreateSubmissionBatchSubmissionsResponse;
import com.docspring.client.model.SubmissionBatch;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for CreateSubmissionBatchResponse
 */
public class CreateSubmissionBatchResponseTest {
    private final CreateSubmissionBatchResponse model = new CreateSubmissionBatchResponse();

    /**
     * Model tests for CreateSubmissionBatchResponse
     */
    @Test
    public void testCreateSubmissionBatchResponse() {
        // TODO: test CreateSubmissionBatchResponse
    }

    /**
     * Test the property 'status'
     */
    @Test
    public void statusTest() {
        // TODO: test status
    }

    /**
     * Test the property 'error'
     */
    @Test
    public void errorTest() {
        // TODO: test error
    }

    /**
     * Test the property 'errors'
     */
    @Test
    public void errorsTest() {
        // TODO: test errors
    }

    /**
     * Test the property 'submissionBatch'
     */
    @Test
    public void submissionBatchTest() {
        // TODO: test submissionBatch
    }

    /**
     * Test the property 'submissions'
     */
    @Test
    public void submissionsTest() {
        // TODO: test submissions
    }

}
