/*
 * API v1
 * DocSpring is a service that helps you fill out and sign PDF templates.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.docspring.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for MoveTemplateData
 */
public class MoveTemplateDataTest {
    private final MoveTemplateData model = new MoveTemplateData();

    /**
     * Model tests for MoveTemplateData
     */
    @Test
    public void testMoveTemplateData() {
        // TODO: test MoveTemplateData
    }

    /**
     * Test the property 'parentFolderId'
     */
    @Test
    public void parentFolderIdTest() {
        // TODO: test parentFolderId
    }

}
