/*
 * API v1
 * DocSpring is a service that helps you fill out and sign PDF templates.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.docspring.client.model;

import com.docspring.client.model.Submission;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for SubmissionBatch
 */
public class SubmissionBatchTest {
    private final SubmissionBatch model = new SubmissionBatch();

    /**
     * Model tests for SubmissionBatch
     */
    @Test
    public void testSubmissionBatch() {
        // TODO: test SubmissionBatch
    }

    /**
     * Test the property 'id'
     */
    @Test
    public void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'totalCount'
     */
    @Test
    public void totalCountTest() {
        // TODO: test totalCount
    }

    /**
     * Test the property 'pendingCount'
     */
    @Test
    public void pendingCountTest() {
        // TODO: test pendingCount
    }

    /**
     * Test the property 'errorCount'
     */
    @Test
    public void errorCountTest() {
        // TODO: test errorCount
    }

    /**
     * Test the property 'completionPercentage'
     */
    @Test
    public void completionPercentageTest() {
        // TODO: test completionPercentage
    }

    /**
     * Test the property 'state'
     */
    @Test
    public void stateTest() {
        // TODO: test state
    }

    /**
     * Test the property 'processedAt'
     */
    @Test
    public void processedAtTest() {
        // TODO: test processedAt
    }

    /**
     * Test the property 'metadata'
     */
    @Test
    public void metadataTest() {
        // TODO: test metadata
    }

    /**
     * Test the property 'submissions'
     */
    @Test
    public void submissionsTest() {
        // TODO: test submissions
    }

}
