/*
 * API v1
 * DocSpring is a service that helps you fill out and sign PDF templates.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.docspring.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.math.BigDecimal;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for Template1Defaults
 */
public class Template1DefaultsTest {
    private final Template1Defaults model = new Template1Defaults();

    /**
     * Model tests for Template1Defaults
     */
    @Test
    public void testTemplate1Defaults() {
        // TODO: test Template1Defaults
    }

    /**
     * Test the property 'color'
     */
    @Test
    public void colorTest() {
        // TODO: test color
    }

    /**
     * Test the property 'fontSize'
     */
    @Test
    public void fontSizeTest() {
        // TODO: test fontSize
    }

    /**
     * Test the property 'typeface'
     */
    @Test
    public void typefaceTest() {
        // TODO: test typeface
    }

}
